### ISSUE TITLE
Service worker should refresh the page if there's a new version

### ISSUE THREAD

**Issue by jkomoros** [jkomoros/card-web#442]
E.g. people who visited the page before concepts were launched get a 404

**Comment by jkomoros** [comment]
https://whatwebcando.today/articles/handling-service-worker-updates/

**Comment by jkomoros** [comment]
https://github.com/GoogleChromeLabs/sw-precache#skipwaiting-boolean

**Comment by jkomoros** [comment]
0130315 didn't fix it

**Comment by jeffposnick** [comment]
👋 @jkomoros 

I'm not completely sure what getting a 404 means in this context, because it looks like your service worker (using the _very_ old `sw-precache` module...) is set up to respond to all navigations with the contents of your `index.html`. So all navigations should result in a valid 200 OK response, but the actual content used to populate your app shell might not match the URL if the currently cached client-side code is too old and doesn't know how to route things properly. Perhaps that's what you meant?

You're correct in that calling `skipWaiting()` from within the service worker forces everything that was out of date to be purged from the cache, and everything's new to be used for subsequent `fetch` events.

There are (at least) two different ways to coordinate using `skipWaiting()` with the client-side code in your web app.

1. Call `skipWaiting()` unconditionally (which is what https://github.com/jkomoros/card-web/commit/01303156c6fa8292ca967332c5b191c5270367be added), *and* reload the current page after the waiting service worker has activated. The reload the page part is what you haven't implemented.

2. Call `skipWaiting()` conditionally, by using `postMessage()` from the client page, in response to a user clicking on something in your UI along the lines of "A new version is available. Click to reload.". This requires a bit more coordination to implement—the client-side code needs to know how to show the toast, the service worker needs to know how to listen for that `postMessage()`. Newer versions of Workbox take care of a lot of that for you; i.e. there's a recipe [here](https://developers.google.com/web/tools/workbox/guides/advanced-recipes#offer_a_page_reload_for_users) that describes that pattern. This approach is described in more generic detail in this [blog post](https://dev.to/thepassle/on-pwa-update-patterns-4fgm).

I think given that this is still using `sw-precache`, and since the jarring aspects of forcing a page to reload probably aren't the _biggest_ issue for a hobby project, I'd go with the first approach. You just need to add the code to your client-side JS to detect a new service worker activating, and forcibly reload the page when that occurs.

You could use [`workbox-window`](https://developers.google.com/web/tools/workbox/modules/workbox-window) to do this (even if you're using `sw-precache` for the actual service worker), but it's also short enough to do via "vanilla" JS, as described in [this Stack Overflow answer](https://stackoverflow.com/a/41896649/385997):

```
navigator.serviceWorker.register('/service-worker.js').then(reg => {
  reg.onupdatefound = () => {
    const installingWorker = reg.installing;
    installingWorker.onstatechange = () => {
      if (installingWorker.state === 'installed' &&
          navigator.serviceWorker.controller) {
        location.reload();
      }
    };
  };
});
```

**Comment by jkomoros** [comment]
Thank you @jeffposnick , this is extremely useful! Sorry, the "404" was using imprecise language since I was capturing thoughts mainly for myself. The whole site loads correctly, but within the UI the user gets my "No such card exists" UI.
